apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: onlinebookstore-ui
  template:
    metadata:
      labels:
        app: onlinebookstore-ui
    spec:
      containers:
      - image: madhavkrishna118/onlinebooking:latest
        name: onlinebookstore-ui
        ports:
        - containerPort: 80
